# Generated by Django 5.1.1 on 2024-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=30)),
                ('movieImage', models.ImageField(upload_to='images/')),
                ('movieGenre', models.CharField(max_length=30)),
                ('movieLanguage', models.CharField(max_length=30)),
                ('movieDescription', models.CharField(max_length=30)),
            ],
        ),
    ]
